name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          BIN_NAME="scylla"                       # 👈 must match Cargo.toml binary
          VERSION="${GITHUB_REF_NAME}"            # e.g. v1.0.0
          TARGET="${{ matrix.target }}"
          OUT_DIR="release"

          mkdir -p $OUT_DIR

          if [[ "$TARGET" == *windows* ]]; then
            cp target/$TARGET/release/${BIN_NAME}.exe $OUT_DIR/
            zip -j $OUT_DIR/${BIN_NAME}-${VERSION}-${TARGET}.zip $OUT_DIR/${BIN_NAME}.exe
            rm $OUT_DIR/${BIN_NAME}.exe
          else
            cp target/$TARGET/release/${BIN_NAME} $OUT_DIR/
            tar -czf $OUT_DIR/${BIN_NAME}-${VERSION}-${TARGET}.tar.gz -C $OUT_DIR ${BIN_NAME}
            rm $OUT_DIR/${BIN_NAME}
          fi

      - name: Generate Checksums
        shell: bash
        run: |
          cd release
          sha256sum * > checksums.txt

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
